# docker compose version
version: "3.2"
services:
  web-wnh:
    environment:
      REDIS_SERVER: redis
      NODE_ENV: production
    build:
      # build container with Dockerfile under the context directory
      context: ./checkin-app
      args:
        NODE_ENV: production
        PORT_HTTP: 8080
        PORT_HTTPS: null
        CONFIG_FILE: config.wnh.mjs
        PROCESS_FILE: process-local.wnh.json
        FAVICON_FILE: favicon.wnh.ico
    ports:
      # host port : container port
      - "9080:8080"
    links:
      - redis
    restart: always
  redis:
    image: redis:alpine
    sysctls:
      # for redis
      net.core.somaxconn: "1024"
    # use redis server with data persistence
    #command: redis-server /data/redis/redis.conf --port 6380 --appendonly yes
    command: redis-server --dir /data/redis --port 6380 --appendonly yes --logfile /data/redis/redis-server.log
    volumes:
      # source host directory will be mounted to target container filesystem directory
      - /data:/data
    ports:
      # host port : container port
      - "6380:6380"
    expose:
      - "6380"
    restart: always
